#!/usr/bin/env bash
set -euo pipefail

if ! command -v jq >/dev/null 2>&1; then
  echo "jq is required" >&2
  exit 1
fi

payload="$(cat)"

host="$(jq -r '.input.host // "localhost"' <<<"${payload}")"
host="${host//$'\n'/}"
host="${host//$'\r'/}"
if [[ -z "${host}" || "${host}" == *'://'*
   || "${host}" == */* || "${host}" == *$'\t'* || "${host}" == *' '* ]]; then
  host="localhost"
fi

scheme="$(jq -r '.input.scheme // empty' <<<"${payload}")"
scheme="${scheme//$'\n'/}"
scheme="${scheme//$'\r'/}"
case "${scheme}" in
  http|https) ;;
  *) scheme="" ;;
esac

split_host="${host}"
split_port=""
if [[ "${host}" == \[*] ]]; then
  if [[ "${host}" =~ ^(\[[^]]+\]):([0-9]+)$ ]]; then
    split_host="${BASH_REMATCH[1]}"
    split_port="${BASH_REMATCH[2]}"
  fi
elif [[ "${host}" =~ ^(.+):([0-9]+)$ ]]; then
  split_host="${BASH_REMATCH[1]}"
  split_port="${BASH_REMATCH[2]}"
fi

if [[ -z "${scheme}" ]]; then
  if [[ "${split_port}" == "80" ]]; then
    scheme="http"
  elif [[ "${split_port}" == "443" ]]; then
    scheme="https"
  fi
fi

host_operator="streq"
host_operand="${host}"
if [[ "${scheme}" == "http" && ( -z "${split_port}" || "${split_port}" == "80" ) ]]; then
  host_operator="rx"
  host_operand="^$(python3 -c 'import re,sys; print(re.escape(sys.argv[1]))' "${split_host}")(:80)?$"
elif [[ "${scheme}" == "https" && ( -z "${split_port}" || "${split_port}" == "443" ) ]]; then
  host_operator="rx"
  host_operand="^$(python3 -c 'import re,sys; print(re.escape(sys.argv[1]))' "${split_host}")(:443)?$"
fi

path="$(jq -r '.input.path // "/"' <<<"${payload}")"
path="${path//$'\n'/}"
path="${path//$'\r'/}"
if [[ "${path}" != /* ]] || [[ "${path}" == *'"'* ]]; then
  path="/"
fi

rule_id="$(jq -r '.input.rule_id // 100004' <<<"${payload}")"
if ! [[ "${rule_id}" =~ ^[0-9]+$ ]]; then
  rule_id="100004"
fi

matched_variable="$(jq -r '.input.matched_variable // "ARGS:q"' <<<"${payload}")"
if ! [[ "${matched_variable}" =~ ^[A-Za-z0-9_.:!]+$ ]]; then
  matched_variable="ARGS:q"
fi

target_path="$(jq -r '.target_path // "tukuyomi.conf"' <<<"${payload}")"
summary="$(jq -r '.input.matched_value // "" | if length > 0 then "Candidate false positive from input sample." else "Candidate false positive event." end' <<<"${payload}")"

jq -n \
  --arg path "${path}" \
  --arg host "${host}" \
  --arg host_operator "${host_operator}" \
  --arg host_operand "${host_operand}" \
  --arg target_path "${target_path}" \
  --arg matched_variable "${matched_variable}" \
  --arg summary "${summary}" \
  --argjson rule_id "${rule_id}" \
  '{
    proposal: {
      id: ("fp-cmd-" + (now|floor|tostring)),
      title: "Scoped false-positive tuning suggestion",
      summary: ($summary + " Scoped to host " + $host + "."),
      reason: "Generated by command provider example script.",
      confidence: 0.86,
      target_path: $target_path,
      rule_line: (
        "SecRule REQUEST_HEADERS:Host \"@" + $host_operator + " " + $host_operand +
        "\" \"id:190321,phase:1,pass,nolog,chain,msg:\u0027tukuyomi fp_tuner scoped exclusion\u0027\"\n" +
        "SecRule REQUEST_URI \"@beginsWith " + $path +
        "\" \"ctl:ruleRemoveTargetById=" +
        ($rule_id|tostring) + ";" + $matched_variable + "\""
      )
    }
  }'
