#!/usr/bin/env bash
set -euo pipefail

if ! command -v jq >/dev/null 2>&1; then
  echo "jq is required" >&2
  exit 1
fi

payload="$(cat)"

path="$(jq -r '.input.path // "/"' <<<"${payload}")"
path="${path//$'\n'/}"
path="${path//$'\r'/}"
if [[ "${path}" != /* ]] || [[ "${path}" == *'"'* ]]; then
  path="/"
fi

rule_id="$(jq -r '.input.rule_id // 100004' <<<"${payload}")"
if ! [[ "${rule_id}" =~ ^[0-9]+$ ]]; then
  rule_id="100004"
fi

matched_variable="$(jq -r '.input.matched_variable // "ARGS:q"' <<<"${payload}")"
if ! [[ "${matched_variable}" =~ ^[A-Za-z0-9_.:!]+$ ]]; then
  matched_variable="ARGS:q"
fi

target_path="$(jq -r '.target_path // "rules/tukuyomi.conf"' <<<"${payload}")"
summary="$(jq -r '.input.matched_value // "" | if length > 0 then "Candidate false positive from input sample." else "Candidate false positive event." end' <<<"${payload}")"

jq -n \
  --arg path "${path}" \
  --arg target_path "${target_path}" \
  --arg matched_variable "${matched_variable}" \
  --arg summary "${summary}" \
  --argjson rule_id "${rule_id}" \
  '{
    proposal: {
      id: ("fp-cmd-" + (now|floor|tostring)),
      title: "Scoped false-positive tuning suggestion",
      summary: $summary,
      reason: "Generated by command provider example script.",
      confidence: 0.86,
      target_path: $target_path,
      rule_line: (
        "SecRule REQUEST_URI \"@beginsWith " + $path +
        "\" \"id:190321,phase:1,pass,nolog,ctl:ruleRemoveTargetById=" +
        ($rule_id|tostring) + ";" + $matched_variable +
        ",msg:\u0027tukuyomi fp_tuner scoped exclusion\u0027\""
      )
    }
  }'
