#!/usr/bin/env bash
set -euo pipefail

if ! command -v jq >/dev/null 2>&1; then
  echo "jq is required" >&2
  exit 1
fi

payload="$(cat)"

host="$(jq -r '.input.host // "example.com"' <<<"${payload}")"
host="${host//$'\n'/}"
host="${host//$'\r'/}"
if [[ -z "${host}" ]] || [[ "${host}" == *'"'* ]]; then
  host="example.com"
fi

scheme="$(jq -r '.input.scheme // ""' <<<"${payload}")"
scheme="${scheme,,}"
if [[ "${scheme}" != "http" && "${scheme}" != "https" ]]; then
  scheme=""
fi

path="$(jq -r '.input.path // "/"' <<<"${payload}")"
path="${path//$'\n'/}"
path="${path//$'\r'/}"
if [[ "${path}" != /* ]] || [[ "${path}" == *'"'* ]]; then
  path="/"
fi

rule_id="$(jq -r '.input.rule_id // 100004' <<<"${payload}")"
if ! [[ "${rule_id}" =~ ^[0-9]+$ ]]; then
  rule_id="100004"
fi

matched_variable="$(jq -r '.input.matched_variable // "ARGS:q"' <<<"${payload}")"
if ! [[ "${matched_variable}" =~ ^[A-Za-z0-9_.:!]+$ ]]; then
  matched_variable="ARGS:q"
fi

target_path="$(jq -r '.target_path // "rules/tukuyomi.conf"' <<<"${payload}")"
summary="$(jq -r '.input.matched_value // "" | if length > 0 then "Candidate false positive from input sample." else "Candidate false positive event." end' <<<"${payload}")"

host_scope_operator="streq"
host_scope_operand="${host}"
host_only="${host%%:*}"
port=""
if [[ "${host}" == *:* ]] && [[ "${host}" != \[* ]]; then
  port="${host##*:}"
fi
if [[ "${scheme}" == "http" && ( -z "${port}" || "${port}" == "80" ) ]]; then
  host_scope_operator="rx"
  host_scope_operand="^$(printf '%s' "${host_only}" | sed 's/[.[\\*^$+?(){|]/\\\\&/g')(:80)?$"
elif [[ "${scheme}" == "https" && ( -z "${port}" || "${port}" == "443" ) ]]; then
  host_scope_operator="rx"
  host_scope_operand="^$(printf '%s' "${host_only}" | sed 's/[.[\\*^$+?(){|]/\\\\&/g')(:443)?$"
fi

jq -n \
  --arg host_scope_operator "${host_scope_operator}" \
  --arg host_scope_operand "${host_scope_operand}" \
  --arg path "${path}" \
  --arg target_path "${target_path}" \
  --arg matched_variable "${matched_variable}" \
  --arg summary "${summary}" \
  --argjson rule_id "${rule_id}" \
  '{
    proposal: {
      id: ("fp-cmd-" + (now|floor|tostring)),
      title: "Scoped false-positive tuning suggestion",
      summary: $summary,
      reason: "Generated by command provider example script.",
      confidence: 0.86,
      target_path: $target_path,
      rule_line: (
        "SecRule REQUEST_HEADERS:Host \"@" + $host_scope_operator + " " + $host_scope_operand +
        "\" \"id:190321,phase:1,pass,nolog,chain,msg:\u0027tukuyomi fp_tuner scoped exclusion\u0027\"\n" +
        "SecRule REQUEST_URI \"@beginsWith " + $path +
        "\" \"ctl:ruleRemoveTargetById=" + ($rule_id|tostring) + ";" + $matched_variable + "\""
      )
    }
  }'
