ALTER TABLE center_devices ADD COLUMN os VARCHAR(32) NOT NULL DEFAULT '';
ALTER TABLE center_devices ADD COLUMN arch VARCHAR(32) NOT NULL DEFAULT '';
ALTER TABLE center_devices ADD COLUMN kernel_version VARCHAR(128) NOT NULL DEFAULT '';
ALTER TABLE center_devices ADD COLUMN distro_id VARCHAR(64) NOT NULL DEFAULT '';
ALTER TABLE center_devices ADD COLUMN distro_id_like VARCHAR(128) NOT NULL DEFAULT '';
ALTER TABLE center_devices ADD COLUMN distro_version VARCHAR(64) NOT NULL DEFAULT '';
