CREATE TABLE IF NOT EXISTS log_archives (
	archive_id VARCHAR(128) NOT NULL PRIMARY KEY,
	source VARCHAR(64) NOT NULL,
	archive_day VARCHAR(10) NOT NULL,
	part INT NOT NULL,
	state VARCHAR(16) NOT NULL,
	storage_backend VARCHAR(32) NOT NULL,
	object_key TEXT NOT NULL,
	meta_object_key TEXT NOT NULL,
	from_ts_unix BIGINT NOT NULL,
	to_ts_unix BIGINT NOT NULL,
	first_event_id BIGINT NOT NULL,
	last_event_id BIGINT NOT NULL,
	row_count BIGINT NOT NULL,
	compressed_bytes BIGINT NOT NULL,
	uncompressed_bytes BIGINT NOT NULL,
	sha256 CHAR(64) NOT NULL,
	error TEXT NOT NULL,
	created_at_unix BIGINT NOT NULL,
	created_at VARCHAR(64) NOT NULL,
	sealed_at_unix BIGINT NOT NULL DEFAULT 0,
	sealed_at VARCHAR(64) NOT NULL DEFAULT '',
	pruned_at_unix BIGINT NOT NULL DEFAULT 0,
	pruned_at VARCHAR(64) NOT NULL DEFAULT '',
	updated_at_unix BIGINT NOT NULL,
	updated_at VARCHAR(64) NOT NULL,
	UNIQUE KEY uq_log_archives_source_day_part (source, archive_day, part),
	KEY idx_log_archives_state (state),
	KEY idx_log_archives_archive_day (archive_day)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
