CREATE TABLE IF NOT EXISTS admin_users (
	user_id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	username VARCHAR(64) NOT NULL,
	username_normalized VARCHAR(64) NOT NULL,
	email VARCHAR(254) NULL,
	email_normalized VARCHAR(254) NULL,
	role VARCHAR(32) NOT NULL,
	password_hash VARCHAR(255) NOT NULL,
	password_algo VARCHAR(32) NOT NULL DEFAULT 'argon2id',
	must_change_password TINYINT(1) NOT NULL DEFAULT 0,
	session_version BIGINT NOT NULL DEFAULT 1,
	disabled_at_unix BIGINT NULL,
	disabled_at VARCHAR(64) NULL,
	last_login_at_unix BIGINT NULL,
	last_login_at VARCHAR(64) NULL,
	created_at_unix BIGINT NOT NULL,
	created_at VARCHAR(64) NOT NULL,
	updated_at_unix BIGINT NOT NULL,
	updated_at VARCHAR(64) NOT NULL,
	UNIQUE KEY uq_admin_users_username_normalized (username_normalized),
	UNIQUE KEY uq_admin_users_email_normalized (email_normalized),
	KEY idx_admin_users_role (role),
	KEY idx_admin_users_disabled_at_unix (disabled_at_unix)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS admin_api_tokens (
	token_id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	user_id BIGINT NOT NULL,
	label VARCHAR(128) NOT NULL,
	token_prefix VARCHAR(32) NOT NULL,
	token_hash VARCHAR(96) NOT NULL,
	scopes_json LONGTEXT NOT NULL,
	expires_at_unix BIGINT NULL,
	expires_at VARCHAR(64) NULL,
	revoked_at_unix BIGINT NULL,
	revoked_at VARCHAR(64) NULL,
	last_used_at_unix BIGINT NULL,
	last_used_at VARCHAR(64) NULL,
	created_at_unix BIGINT NOT NULL,
	created_at VARCHAR(64) NOT NULL,
	UNIQUE KEY uq_admin_api_tokens_token_prefix (token_prefix),
	UNIQUE KEY uq_admin_api_tokens_token_hash (token_hash),
	KEY idx_admin_api_tokens_user_id (user_id),
	KEY idx_admin_api_tokens_expires_at_unix (expires_at_unix),
	KEY idx_admin_api_tokens_revoked_at_unix (revoked_at_unix),
	CONSTRAINT fk_admin_api_tokens_user_id FOREIGN KEY (user_id) REFERENCES admin_users(user_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS admin_sessions (
	session_id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	user_id BIGINT NOT NULL,
	session_token_hash VARCHAR(96) NOT NULL,
	csrf_token_hash VARCHAR(96) NOT NULL,
	session_version BIGINT NOT NULL,
	expires_at_unix BIGINT NOT NULL,
	expires_at VARCHAR(64) NOT NULL,
	revoked_at_unix BIGINT NULL,
	revoked_at VARCHAR(64) NULL,
	last_seen_at_unix BIGINT NOT NULL,
	last_seen_at VARCHAR(64) NOT NULL,
	created_at_unix BIGINT NOT NULL,
	created_at VARCHAR(64) NOT NULL,
	UNIQUE KEY uq_admin_sessions_session_token_hash (session_token_hash),
	KEY idx_admin_sessions_user_id (user_id),
	KEY idx_admin_sessions_expires_at_unix (expires_at_unix),
	KEY idx_admin_sessions_revoked_at_unix (revoked_at_unix),
	CONSTRAINT fk_admin_sessions_user_id FOREIGN KEY (user_id) REFERENCES admin_users(user_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS admin_auth_audit (
	event_id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	event_type VARCHAR(64) NOT NULL,
	user_id BIGINT NULL,
	username VARCHAR(64) NULL,
	auth_kind VARCHAR(32) NOT NULL,
	auth_credential_id VARCHAR(128) NULL,
	success TINYINT(1) NOT NULL,
	ip VARCHAR(64) NULL,
	user_agent TEXT NULL,
	metadata_json LONGTEXT NOT NULL,
	created_at_unix BIGINT NOT NULL,
	created_at VARCHAR(64) NOT NULL,
	KEY idx_admin_auth_audit_event_created (event_type, created_at_unix),
	KEY idx_admin_auth_audit_user_created (user_id, created_at_unix),
	KEY idx_admin_auth_audit_success_created (success, created_at_unix),
	CONSTRAINT fk_admin_auth_audit_user_id FOREIGN KEY (user_id) REFERENCES admin_users(user_id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
