ALTER TABLE vhosts ADD COLUMN enabled INT NOT NULL DEFAULT 0;
ALTER TABLE vhosts ADD COLUMN command VARCHAR(1024) NOT NULL DEFAULT '';
ALTER TABLE vhosts ADD COLUMN args_json TEXT NULL;
ALTER TABLE vhosts ADD COLUMN working_dir VARCHAR(1024) NOT NULL DEFAULT '';
ALTER TABLE vhosts ADD COLUMN run_user VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE vhosts ADD COLUMN run_group VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE vhosts ADD COLUMN restart_policy VARCHAR(32) NOT NULL DEFAULT '';
ALTER TABLE vhosts ADD COLUMN graceful_stop_sec INT NOT NULL DEFAULT 0;
ALTER TABLE vhosts ADD COLUMN persistent_paths_json TEXT NULL;
